### PR TITLE
Added support for PE/COFF object files

### LINKED ISSUE #36: Doesn't work on COFF object files
It gives `Unknown magic: 0x68664`. It works fine on PE executable files.

### PR DESCRIPTION
**Pull request by koutheir**
This fixes the issue for this project. However, the issue stems [in the goblin crate](https://github.com/m4b/goblin/issues/324), and should ideally be fixed there.

Closes #36.

### CODE REVIEW

**Comment by koutheir** [comment]
@m4b, can you please review?

**Comment by m4b** [comment]
This looks great thanks for the PR!

should we do a release soon or are there other pending issues that a new goblin release might help with ?

**Comment by koutheir** [comment]
It makes sense to release bingrep now. I hope the issue gets resolved in goblin too.

**Comment by m4b** [comment]
Ok I’ll prepare a release asap. Also a bug was filed in goblin for this right ?

**Comment by koutheir** [comment]
Yes, [this one](https://github.com/m4b/goblin/issues/324).

**Pull request merged**
